name: Sign

on:
  workflow_dispatch:
  
env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'false'
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'
  
jobs:
  ba_ra_ra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.13.1'
      - run: go version
      - run: go run main.go secrets.APPVER secrets.UID secrets.COOKIE
