name: Sign

on:
  # schedule:
  #   - cron: "0 22 * * *"
  workflow_dispatch:
  
env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'false'
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'
  
jobs:
  ba_ra_ra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibrt/golang-github-action@v1
        with:
          go-version: 1.16
          go-packages: |
            github.com/gofrs/uuid
      - run:  go run main.go ${{ secrets.APPVER }} ${{ secrets.UID }} ${{ secrets.COOKIE }}
