name: Sign

on:
  # schedule:
  #   - cron: "0 22 * * *"
  workflow_dispatch:
  
env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'false'
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'
  
jobs:
  ba_ra_ra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.13.1'
      - run:  go version
      - run:  go get -v -u github.com/gofrs/uuid
      - run:  ls /opt/hostedtoolcache/go/1.16.7/x64/src/github.com
#       - run:  go run main.go ${{ secrets.APPVER }} ${{ secrets.UID }} ${{ secrets.COOKIE }}
      - run:  go help modules
